---
site_name: KEH Policy Methods Library
site_description: A library of methods to check GitHub Usage Policy compliance of GitHub repositories, to be used by the KEH team at ONS.
repo_url: https://github.com/ONS-Innovation/keh-policy-methods-library
repo_name: KEH Policy Methods Library
nav:
  - Home: index.md
  - Implementation Examples: implementation_examples.md
  - Documentation: documentation.md
  - GitHub Modules:
      - Overview: github/overview.md
      - Auth: github/auth.md
      - Clients: github/clients.md
  - Policy Checks:
      - Overview: checks/overview.md
      - Naming Convention: checks/naming_convention.md
      - Inactivity: checks/inactivity.md
      - Repository Access: checks/repository_access.md
      - Readme: checks/readme.md
      - Dependabot: checks/dependabot.md
  - Dev Guides:
      - Adding Checks: dev_guides/adding_checks.md
      - Testing New Functionality: dev_guides/testing_new_functionality.md
theme:
  name: material
  language: en
  palette:
    # toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - header.autohide
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - mkdocstrings:
      default_handler: python
