---
name: Linting and Formatting
on:
  push:
    branches: [main]
    paths:
      - src/**
      - tests/**
  pull_request:
    branches: [main]
    paths:
      - src/**
      - tests/**
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: poetry
      - name: Install dependencies
        run: |
          make install-dev
      - name: Run linters
        run: |
          make lint
